# Generated by Django 3.2.13 on 2023-04-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeinterval', models.CharField(blank=True, max_length=200)),
                ('shifttype', models.CharField(blank=True, max_length=200)),
                ('constraints', models.CharField(choices=[('soft', 'Soft'), ('Hard', 'hard')], default='soft', max_length=200)),
                ('penalty_cost', models.IntegerField(choices=[(20, 20), (10, 10)], default=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.nurses')),
            ],
        ),
    ]
