# Generated by Django 3.2.13 on 2023-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurses',
            name='hours_available',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nurses',
            name='skill_level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
