# Generated by Django 3.2.13 on 2023-04-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_shifts_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.nurses')),
            ],
        ),
        migrations.AddField(
            model_name='nurses',
            name='available_days',
            field=models.ManyToManyField(to='backend.Availability'),
        ),
    ]
