# Generated by Django 3.2.13 on 2023-04-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.days'),
        ),
    ]
