# Generated by Django 3.2.13 on 2023-04-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_availability_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='available_days',
        ),
        migrations.AddField(
            model_name='nurses',
            name='available_days',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.days'),
            preserve_default=False,
        ),
    ]
