# Generated by Django 3.2.13 on 2023-04-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230420_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='available_days',
        ),
        migrations.AddField(
            model_name='nurses',
            name='available_days',
            field=models.ManyToManyField(to='backend.Days'),
        ),
    ]
