# Generated by Django 3.2.13 on 2023-04-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230420_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.nurses')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shifts')),
            ],
        ),
    ]
