# Generated by Django 3.2.13 on 2023-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_shiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='shifttime',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=200),
        ),
    ]
