# Generated by Django 3.2.13 on 2023-04-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_shiftassignment_unique_together'),
    ]

    operations = [
    ]
