# Generated by Django 3.2.13 on 2023-04-20 13:06

from django.db import migrations

from django.db import migrations

def create_default_days(apps, schema_editor):
    Days = apps.get_model('backend', 'Days')
    Days.objects.create(name='Monday')
    Days.objects.create(name='Tuesday')
    Days.objects.create(name='Wednesday')
    Days.objects.create(name='Thursday')
    Days.objects.create(name='Friday')
    Days.objects.create(name='Saturday')
    Days.objects.create(name='Sunday')

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20230420_1557'),
    ]

    operations = [
        migrations.RunPython(create_default_days),
    ]



# class Migration(migrations.Migration):

#     dependencies = [
#         ('backend', '0009_auto_20230420_1557'),
#     ]

#     operations = [
#     ]
