# Generated by Django 3.2.13 on 2023-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_add_default_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='coverage_demand',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='constraints',
            field=models.CharField(choices=[('soft', 'Soft'), ('hard', 'Hard')], default='soft', max_length=200),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shifttype',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=200),
        ),
    ]
