# Generated by Django 3.2.13 on 2023-05-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_available_day_nurses_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='available_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.days'),
        ),
    ]
