# Generated by Django 3.2.13 on 2023-05-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_nurses_available_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='available_days',
        ),
        migrations.AddField(
            model_name='nurses',
            name='available_days',
            field=models.ManyToManyField(to='backend.Days'),
        ),
    ]
