# Generated by Django 3.2.13 on 2023-05-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20230504_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='available_days',
        ),
        migrations.AddField(
            model_name='nurses',
            name='available_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.days'),
        ),
    ]
