# Generated by Django 3.2.13 on 2023-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_nurses_hours_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='days',
            field=models.ManyToManyField(to='backend.Days'),
        ),
    ]
