# Generated by Django 3.2.13 on 2023-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_shiftassignment_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=200),
        ),
    ]
