# Generated by Django 3.2.13 on 2023-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_shiftassignment_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='penalty_cost',
            field=models.IntegerField(default=10),
        ),
    ]
